apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-rmq-autoscaler
  namespace: k8s-rmq-autoscaler
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-rmq-autoscaler
  namespace: k8s-rmq-autoscaler
rules:
- apiGroups:
  - apps
  - extensions
  - ""
  resources:
  - deployments
  - namespaces
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-rmq-autoscaler
  namespace: k8s-rmq-autoscaler
roleRef:
  kind: ClusterRole
  name: k8s-rmq-autoscaler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: k8s-rmq-autoscaler
  namespace: k8s-rmq-autoscaler
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-rmq-autoscaler
  namespace: k8s-rmq-autoscaler
spec:
  containers:
  - image: xcid/k8s-rmq-autoscaler:latest
    imagePullPolicy: Always
    name: k8s-rmq-autoscaler
    env:
    - name: RMQ_URL
      value: http://your-rmq.namespace.svc.cluster.local:15672
    - name: RMQ_USER
      value: user
    envFrom:
    - secretRef:
        name: rmq-credentials
    resources:
      limits:
        memory: 100M
      requests:
        memory: 100M
    tty: true
  serviceAccountName: k8s-rmq-autoscaler
  restartPolicy: Always
